name = "daily-stock-analysis"
compatibility_date = "2024-09-01"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"
ADMIN_EMAIL = "admin@deltaharvest.local"
ADMIN_NOTIFICATION_EMAIL = "fjmaresca@gmail.com"
SESSION_SECRET = "dh_sec_9f82c4a17b3e0d8f5a6b2c4e1d7a9b3c_prod2026"

[[d1_databases]]
binding = "DB"
database_name = "deltaharvest-db"
database_id = "496fc81e-9aef-4e93-b5c4-20d1ee9722ed"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "5b184cbe2a4449f6a32be470b97c6338"
