/**
 * Executive Portfolio Health Digest & Multi-Format Report Generator
 *
 * Consolidates institutional derivatives portfolio telemetry into a printable
 * executive briefing and downloadable Markdown/JSON report.
 */

export interface ExecutiveDigestMetrics {
  dateStr: string;
  netLiquidity: number;
  freeCash: number;
  cashReservePct: number;
  dailyTheta: number;
  projectedMonthlyCashflow: number;
  betaWeightedDelta: number;
  directionalBias: 'BULLISH' | 'NEUTRAL' | 'DEFENSIVE';
  complianceHealthScore: number; // 0 - 100
  totalPositions: number;
  safePositions: number;
  threatenedPositions: number;
  regTMarginUsed: number;
  portfolioMarginUsed: number;
  capitalReliefPct: number;
  winRatePct: number;
  upcomingEarningsCount: number;
}

export function getSampleExecutiveMetrics(): ExecutiveDigestMetrics {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return {
    dateStr,
    netLiquidity: 185420,
    freeCash: 64200,
    cashReservePct: 34.6,
    dailyTheta: 142.50,
    projectedMonthlyCashflow: 4275.0,
    betaWeightedDelta: 48.2,
    directionalBias: 'NEUTRAL',
    complianceHealthScore: 94,
    totalPositions: 8,
    safePositions: 6,
    threatenedPositions: 2,
    regTMarginUsed: 78500,
    portfolioMarginUsed: 31400,
    capitalReliefPct: 60.0,
    winRatePct: 88.5,
    upcomingEarningsCount: 1,
  };
}

export function generateMarkdownExecutiveReport(m: ExecutiveDigestMetrics): string {
  return `# DELTAHARVEST EXECUTIVE PORTFOLIO HEALTH BRIEFING
**Date:** ${m.dateStr}  
**System:** DeltaHarvest Institutional Income & Risk Engine  
**Compliance Health Score:** ${m.complianceHealthScore} / 100  

---

## 1. Executive Summary & Capital Allocation
- **Net Liquidation Value:** $${m.netLiquidity.toLocaleString()}
- **Cash Reserves / Dry Powder:** $${m.freeCash.toLocaleString()} (${m.cashReservePct}% of Portfolio)
- **Daily Theta Harvest:** +$${m.dailyTheta.toFixed(2)}/day (Projected Monthly Run-Rate: $${m.projectedMonthlyCashflow.toLocaleString()})
- **SPY Beta-Weighted Delta:** +${m.betaWeightedDelta}Δ (${m.directionalBias})
- **Trailing 12-Month Win Rate:** ${m.winRatePct}%

---

## 2. Margin Efficiency & Capital Relief (TIMS vs Reg-T)
- **Traditional Reg-T Margin Commitment:** $${m.regTMarginUsed.toLocaleString()}
- **Portfolio Margin (TIMS Risk-Based):** $${m.portfolioMarginUsed.toLocaleString()}
- **Liberated Purchasing Power:** **${m.capitalReliefPct}% Capital Relief** ($${(m.regTMarginUsed - m.portfolioMarginUsed).toLocaleString()} Free Cash)

---

## 3. Threat Assessment & Defensive Action Register
- **Active Open Positions:** ${m.totalPositions}
- **Safe (Delta < 0.30):** ${m.safePositions}
- **Threatened (Delta >= 0.40):** ${m.threatenedPositions}
- **Upcoming Earnings in 7 Days:** ${m.upcomingEarningsCount}
- **Defensive Protocol:** Enforce mandatory 0.50 Delta Roll Out & Down rule for net credit before weekend theta decay.

---
*Generated by DeltaHarvest. All rights reserved.*
`;
}
