# -*- coding: utf-8 -*-
"""
Backend schema and processor for Daily Stock Analysis.
Formats unstructured LLM outputs into a high-density, front-end ready JSON payload.
"""

from typing import List, Optional
from pydantic import BaseModel, Field, computed_field


class TradeSetup(BaseModel):
    ticker: str
    company_name: Optional[str] = None
    market: str = Field(default="US", description="US, HK, CN, etc.")
    bias: str = Field(description="BULLISH, BEARISH, or NEUTRAL")
    conviction_score: float = Field(ge=0, le=10, description="AI confidence score")

    current_price: float
    entry_price: float
    stop_loss: float
    take_profit: float

    catalyst: str
    risk_summary: str
    action_checklist: List[str]
    raw_markdown: str

    @computed_field
    @property
    def risk_reward_ratio(self) -> float:
        """Calculates expected R:R for active trading validation."""
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        if risk == 0:
            return 0.0
        return round(reward / risk, 2)

    @computed_field
    @property
    def setup_grade(self) -> str:
        """Assigns an institutional-grade classification."""
        if self.conviction_score >= 8.0 and self.risk_reward_ratio >= 2.0:
            return "Tier 1 (High Conviction)"
        elif self.conviction_score >= 6.5 and self.risk_reward_ratio >= 1.5:
            return "Tier 2 (Actionable)"
        return "Tier 3 (Watch Only)"


class DailyDashboardPayload(BaseModel):
    report_date: str
    market_phase: str
    vix_level: Optional[float] = None
    analyzed_count: int
    bullish_count: int
    bearish_count: int
    trades: List[TradeSetup]


# FastAPI Endpoint Transformation
def parse_llm_record_to_ui(raw_analysis_dict: dict) -> TradeSetup:
    """
    Adapter function that converts the raw JSON/dict generated by DSA's LLM engine
    into the strongly-typed, frontend-ready TradeSetup model.
    """
    return TradeSetup(
        ticker=str(raw_analysis_dict.get("ticker", "")).upper(),
        company_name=raw_analysis_dict.get("name") or raw_analysis_dict.get("stock_name"),
        market=str(raw_analysis_dict.get("market", "US")).upper(),
        bias=str(raw_analysis_dict.get("bias", "NEUTRAL")).upper(),
        conviction_score=float(raw_analysis_dict.get("score", raw_analysis_dict.get("sentiment_score", 5.0))),
        current_price=float(raw_analysis_dict.get("close", raw_analysis_dict.get("current_price", 0.0))),
        entry_price=float(raw_analysis_dict.get("buy_point", raw_analysis_dict.get("entry_price", 0.0))),
        stop_loss=float(raw_analysis_dict.get("stop_loss", 0.0)),
        take_profit=float(raw_analysis_dict.get("target_price", raw_analysis_dict.get("take_profit", 0.0))),
        catalyst=raw_analysis_dict.get("core_catalyst") or raw_analysis_dict.get("catalyst") or "No catalyst identified",
        risk_summary=raw_analysis_dict.get("risk_warning") or raw_analysis_dict.get("risk_summary") or "Standard market risk",
        action_checklist=raw_analysis_dict.get("checklist") or raw_analysis_dict.get("action_checklist") or [],
        raw_markdown=raw_analysis_dict.get("full_markdown") or raw_analysis_dict.get("raw_markdown") or ""
    )
